// supabase/functions/umrah-lead/index.ts
//
// Menggantikan /api/umrah-lead di Server_bich_payment.js (Express/Midtrans -
// sudah tidak dipakai lagi setelah migrasi ke iPaymu/Edge Functions).
//
// PERBAIKAN dari versi lama: handler Express yang lama TIDAK PERNAH benar-
// benar menyimpan lead ke database - cuma console.log dengan komentar
// "TODO: simpan ke database sungguhan". Function ini benar-benar insert ke
// tabel umrah_leads (lihat SQL CREATE TABLE di bawah untuk dijalankan dulu
// di Supabase SQL Editor sebelum deploy function ini).
//
// Deploy:
//   supabase functions deploy umrah-lead
//
// SQL yang WAJIB dijalankan dulu (sekali saja) di Supabase SQL Editor:
//
//   create table public.umrah_leads (
//     id bigint generated by default as identity primary key,
//     nama text not null,
//     whatsapp text not null,
//     paket text null,
//     status text not null default 'BARU',
//     created_at timestamptz not null default now()
//   );
//   alter table public.umrah_leads enable row level security;
//   -- TIDAK ADA policy untuk anon/authenticated di tabel ini sama sekali -
//   -- artinya publik tidak bisa baca/tulis langsung, cuma service_role
//   -- (dipakai function ini) yang bisa akses. Ini yang kita mau: form
//   -- publik cuma boleh "kirim" lewat function, tidak boleh baca daftar
//   -- lead orang lain atau nulis langsung ke tabel.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Rate limit ringan in-memory per-instance. CATATAN JUJUR: Edge Function
// bisa jalan di banyak instance paralel (tidak seperti server Express yang
// selalu satu proses), jadi ini TIDAK menjamin batas global yang ketat -
// tapi tetap jadi penghalang murah untuk spam kasar dari satu sumber yang
// kebetulan kena instance yang sama. Untuk proteksi lebih serius, taruh di
// depan Cloudflare/WAF atau pakai Supabase rate limiting di level project.
const submitTimestamps = new Map<string, number[]>();
const RATE_LIMIT_MAX = 5;
const RATE_LIMIT_WINDOW_MS = 60 * 1000;

function isRateLimited(ip: string): boolean {
  const now = Date.now();
  const timestamps = (submitTimestamps.get(ip) || []).filter((t) => now - t < RATE_LIMIT_WINDOW_MS);
  timestamps.push(now);
  submitTimestamps.set(ip, timestamps);
  return timestamps.length > RATE_LIMIT_MAX;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const ip = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";
    if (isRateLimited(ip)) {
      return json({ error: "Terlalu banyak percobaan. Coba lagi sebentar lagi." }, 429);
    }

    const body = await req.json();
    const { nama, whatsapp, paket } = body;

    if (!nama || typeof nama !== "string" || !nama.trim()) {
      return json({ error: "Nama wajib diisi." }, 400);
    }
    if (!whatsapp || typeof whatsapp !== "string" || !whatsapp.trim()) {
      return json({ error: "Nomor WhatsApp wajib diisi." }, 400);
    }

    const { error } = await supabaseAdmin.from("umrah_leads").insert([{
      nama: nama.trim().slice(0, 200),
      whatsapp: whatsapp.trim().slice(0, 30),
      paket: typeof paket === "string" ? paket.trim().slice(0, 200) : null,
      status: "BARU",
    }]);

    if (error) {
      console.error("[umrah-lead] Gagal insert:", error);
      return json({ error: "Gagal menyimpan data. Coba lagi." }, 500);
    }

    return json({ ok: true });

  } catch (err) {
    console.error("[umrah-lead] Error:", err);
    return json({ error: String(err) }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}